spring.application.name=corrida-treino

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/corrida_treino
spring.datasource.username=postgres
spring.datasource.password=22501077
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Porta da aplicação
server.port=8080

# JWT
jwt.secret=3cF7gK9mN2pQ5rT8vX1yA4bD6eH0jL3nP6qS9uW2zA5cE8fI1kM4oR7tV0xY3z
jwt.expiration=86400000