spring.application.name=corrida-treino

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_pacex}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:22501077}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:3cF7gK9mN2pQ5rT8vX1yA4bD6eH0jL3nP6qS9uW2zA5cE8fI1kM4oR7tV0xY3z}
jwt.expiration=${JWT_EXPIRATION:86400000}